[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "apiphany"
version = "3.0.0"
authors = [
    { name="Vatsa", email="228140210+svr-s@users.noreply.github.com" },
]
description = "Apiphany is a high-performance API orchestration engine. It transforms the chaotic process of extracting data from complex REST and GraphQL APIs into a clean, strictly-typed, and fully declarative workflow. Powered by `httpx` and `asyncio`, Apiphany tears through deeply chained API requests concurrently without ever triggering rate limits, handles massive multi-page payloads automatically, and seamlessly unpacks deeply nested JSON blobs into pristine Pandas DataFrames or SQL tables."
readme = "README.md"
requires-python = ">=3.8"

[project.urls]
Repository = "https://github.com/svr-s/apiphany"

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "httpx>=0.24.0",
    "aiolimiter>=1.0.0",
    "pydantic>=2.0.0",
    "python-json-logger>=2.0.0"
]

[project.optional-dependencies]
aws = ["boto3>=1.26.0"]
sql = ["pandas>=1.5.0", "sqlalchemy>=2.0.0"]
